services:
  - type: web
    name: sleep-ai
    env: python
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt && pip install gunicorn==20.1.0
    startCommand: python -m gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: OPENAI_API_KEY
        fromService:
          name: openai-secrets
          type: secret
          property: apiKey
      - key: FLASK_ENV
        value: production
    plan: free
